// src/pages/Index.tsx
import Button from '../components/Button';
import IconBxCheckDouble from '../icons/IconBxCheckDouble';
import IconBxCog from '../icons/IconBxCog';
import IconBxHistory from '../icons/IconBxHistory';
import LastWeek from '../components/LastWeek';
import Page from '../components/Page';
import React, { useCallback, useContext } from 'react';
import WarningBox from '../components/WarningBox';
import styles from './Index.module.scss';
import { UserSettingsContext } from '../contexts/UserSettingsContext';
import { useNavigate } from 'react-router';

const PWA_WARNING_KEY = "pwa-warning";

const IS_PWA =
  (window.matchMedia &&
    window.matchMedia("(display-mode: standalone)").matches) ||
  window.navigator["standalone"] != null;

export default function Index(): JSX.Element {
  const navigate = useNavigate();
  const { userSettings, setUserSettings } = useContext(UserSettingsContext);

  const closePwaWarning = useCallback(async () => {
    if (userSettings != null &&
      userSettings.dismissedInfo.indexOf(PWA_WARNING_KEY) < 0) {
      userSettings.dismissedInfo.push(PWA_WARNING_KEY);
      await setUserSettings(userSettings);
    }
  }, [userSettings]);

  return (
    <Page
      header={
        <div className={styles.header}>
          <div style={{ flex: 1 }}></div>
          <Button onClick={() => navigate("/settings")} icon={<IconBxCog />} />
        </div>
      }
      footer={
        <div className={styles.footer}>Build version %BUILD_CHECKSUM%</div>
      }>
      {
        !IS_PWA && userSettings?.dismissedInfo.indexOf(PWA_WARNING_KEY) === -1 &&
        <WarningBox onCloseClicked={closePwaWarning}>
          <p>
            This app is designed to be installed by Google Chrome as a Progressive
            Web App.
          </p>
          <p>
            <a
              href="https://support.google.com/chrome/answer/9658361"
              target="_blank"
              rel="noreferrer"
            >
              Click here for more details.
            </a>
          </p>
        </WarningBox>
      }

      <LastWeek />

      <Button
        onClick={() => navigate("/checkin")}
        icon={<IconBxCheckDouble fontSize={24} />}>
        Check-In
      </Button>

      <Button
        onClick={() => navigate("/history")}
        icon={<IconBxHistory fontSize={24} />}>
        History
      </Button>
    </Page>
  );
}

// src/pages/Index.svelte
<script lang="ts">
  import BiCalendar from "svelte-icons-pack/bi/BiCalendar";
  import BiCheckDouble from "svelte-icons-pack/bi/BiCheckDouble";
  import BiCog from "svelte-icons-pack/bi/BiCog";
  import BiHistory from "svelte-icons-pack/bi/BiHistory";
  import Button from "../components/Button.svelte";
  import Icon from "../components/Icon.svelte";
  import LastWeek from "../components/LastWeek.svelte";
  import Page from "../components/Page.svelte";
  import WarningBox from "../components/WarningBox.svelte";
  import { transitionTo } from "../navigation";
  import {
    setUserSettings,
    UserSettings,
    userSettingsWatcher,
  } from "../storage/userSettings";

  const pwaWarningKey = "pwa-warning";

  const isPwa =
    (window.matchMedia &&
      window.matchMedia("(display-mode: standalone)").matches) ||
    window.navigator["standalone"] != null;

  let userSettings: UserSettings | undefined;
  userSettingsWatcher.subscribe((value) => (userSettings = value));

  async function closePwaWarning(): Promise<void> {
    if (userSettings?.dismissedInfo.indexOf(pwaWarningKey) < 0) {
      userSettings.dismissedInfo.push(pwaWarningKey);
      await setUserSettings(userSettings);
    }
  }
</script>

<Page globalClass="index-content">
  <div slot="header" class="header">
    <div style="flex: 1" />
    <Button onClick={() => transitionTo("settings", "fade-push")}>
      <Icon slot="icon" src={BiCog} color="currentColor" viewBox="0 0 24 24" />
    </Button>
  </div>

  {#if !isPwa && userSettings?.dismissedInfo.indexOf(pwaWarningKey) < 0}
    <WarningBox onCloseClicked={closePwaWarning}>
      <p>
        This app is designed to be installed by Google Chrome as a Progressive
        Web App.
      </p>
      <p>
        <a
          href="https://support.google.com/chrome/answer/9658361"
          target="_blank"
          rel="noreferrer"
        >
          Click here for more details.
        </a>
      </p>
    </WarningBox>
  {/if}

  <LastWeek />

  <Button onClick={() => transitionTo("check-in", "slide-left")}>
    <Icon
      slot="icon"
      src={BiCheckDouble}
      size="24"
      viewBox="0 0 24 24"
      color="currentColor"
    />
    Check-In
  </Button>
  <Button onClick={() => transitionTo("history", "slide-left")}>
    <Icon
      slot="icon"
      src={BiHistory}
      color="currentColor"
      viewBox="0 0 24 24"
    />
    History
  </Button>
  <div class="footer" slot="footer">Build version %BUILD_CHECKSUM%</div>
</Page>

<style>
  .header {
    display: flex;
    flex-direction: row;
  }

  :global(.index-content) {
    display: flex;
    flex-direction: column;
    justify-content: space-around;
  }

  .footer {
    font-weight: 300;
    font-size: 12px;
  }
</style>
