// src/pages/Settings.svelte
<script lang="ts">
  import Button from "../components/Button.svelte";
  import Checkbox from "../components/Checkbox.svelte";
  import Page from "../components/Page.svelte";
  import {
    UserSettings,
    setUserSettings,
    userSettingsWatcher,
  } from "../storage/userSettings";
  import { clearAllCaches } from "../storage/cache";
  import { getSWRegistration } from "../serviceWorker/clientSide";
  import { prefersDarkMode } from "../theme";
  import { transitionTo } from "../navigation";

  const forceUpdate = async () => {
    await clearAllCaches();
    const registration = await getSWRegistration();
    await registration.update();
    location.reload();
  };

  let userSettings: UserSettings;
  userSettingsWatcher.subscribe((value) => {
    userSettings = value;
  });

  const setPrefersDarkMode = (preferDarkMode: boolean): void => {
    setUserSettings(
      Object.assign({}, userSettings, { preferDarkMode: preferDarkMode })
    );
  };

  const checksumPromise = fetch("/real_manifest.json")
    .then((response) => {
      if (!response.ok) {
        throw new Error("Could not fetch real manifest!");
      } else {
        return response.json();
      }
    })
    .then((json) => json["Checksum"]);
</script>

<Page>
  <h1 slot="header">Settings</h1>

  <div class="contents">
    <h2>Theme</h2>
    <div
      class="checkOption"
      on:click={() => setPrefersDarkMode(!prefersDarkMode(userSettings))}
      on:keypress={() => setPrefersDarkMode(!prefersDarkMode(userSettings))}
    >
      <Checkbox
        value={prefersDarkMode(userSettings)}
        onClick={() => setPrefersDarkMode(!prefersDarkMode(userSettings))}
      />
      Dark Mode
    </div>

    <h2>Advanced</h2>

    {#await checksumPromise}
      <p>Loading current checksum...</p>
      <Button disabled={true}>Force app update</Button>
    {:then checksum}
      <p>Latest checksum: {checksum}</p>
      {#if checksum === "%BUILD_CHECKSUM%"}
        <Button disabled={true}>App up to date</Button>
      {:else}
        <Button onClick={forceUpdate}>Force app update</Button>
      {/if}
    {/await}
  </div>

  <div slot="footer" class="footer buttonRow">
    <Button onClick={() => transitionTo("index", "fade-pop")} flex="1">
      Done
    </Button>
  </div>
</Page>

<style>
  .contents {
    display: flex;
    flex-direction: column;
    gap: var(--padding-small);
  }
  .buttonRow {
    display: flex;
    flex-direction: row;
    gap: var(--padding-med);
    width: 100%;
  }
  .checkOption {
    align-items: center;
    cursor: pointer;
    display: flex;
    flex-direction: row;
    gap: var(--padding-med);
    justify-content: start;
  }
  .footer {
    padding-top: var(--padding-med);
  }
</style>

// src/pages/Settings.tsx
import Button from '../components/Button';
import Page from '../components/Page';
import React, { useContext, useEffect, useState } from 'react';
import Switch from '../components/Switch';
import styles from './Settings.module.scss';
import { UserSettingsContext } from '../contexts/UserSettingsContext';
import { clearAllCaches } from "../storage/cache";
import { getSWRegistration } from "../serviceWorker/clientSide";
import { useNavigate } from 'react-router';

const CURRENT_CHECKSUM = '%BUILD_CHECKSUM%';

export default function Settings(): JSX.Element {
  const { userSettings, setUserSettings } = useContext(UserSettingsContext);
  const navigate = useNavigate();
  const [checksum, setChecksum] = useState<string | null>(null);

  useEffect(() => {
    fetch('/real_manifest.json')
      .then(response => {
        if (!response.ok) {
          throw new Error('Could not fetch real manifest!');
        } else {
          return response.json();
        }
      })
      .then(json => json['Checksum'])
      .then(setChecksum);
  }, []);

  const updateEnabled = checksum != null && checksum !== CURRENT_CHECKSUM;
  const prefersDarkMode = userSettings?.preferDarkMode != null ?
    userSettings.preferDarkMode :
    document.body.classList.contains('dark');

  return (
    <Page
      header={<h1>Settings</h1>}
      footer={
        <div slot="footer" className={`${styles.footer} ${styles.buttonRow}`}>
          <Button onClick={() => navigate('/')} flex="1">
            Done
          </Button>
        </div>
      }>
      <div className={styles.contents}>
        <h2>Theme</h2>
        <Switch
          value={prefersDarkMode}
          onClick={(value) => setUserSettings(
            Object.assign({}, userSettings, { preferDarkMode: value }))}>
          Dark Mode
        </Switch>

        <h2>Advanced</h2>
        {
          checksum == null ?
            <p>Loading current checksum...</p> :
            <p>Latest checksum: {checksum}</p>
        }
        <Button
          onClick={forceUpdate}
          disabled={!updateEnabled}>
          Force App Update
        </Button>

      </div>
    </Page>
  );
}

async function forceUpdate() {
  await clearAllCaches();
  const registration = await getSWRegistration();
  await registration.update();
  location.reload();
};
